services:
  burgerorderer:
    image: burgerorderer
    build: ./Containers/burger_orderer
    ports: 
      - 8000:8000
    volumes: 
      - ./Containers/burgerorderer:/app
    environment:
      KITCHENVIEW_HOST: "kitchenview:5000"
    
    kitchenview:
      image: kitchenview
      build: ./Containers/kitchen_view
      ports:
        - 5000:5000
      volumes:
        - ./Containers/kitchenview:/app