services:
  burgerorderer:
    image: burgerorderer
    build: ./Containers/burger_orderer
    ports: 
      - 8000:8000
    volumes: 
      - ./Containers/burger_orderer:/app
    environment:
      KITCHENVIEW_HOST: "kitchenview:5000"
    networks:
    - burgernetwork
    
  kitchenview:
    image: kitchenview
    build: ./Containers/kitchen_view
    ports:
      - 5000:5000
    volumes:
      - ./Containers/kitchen_view:/app

  menustore:
    image: mysql:latest
    #build: ./Containers/db
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: bestgroupever
    
  adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080

networks:
  burgernetwork:
    driver: bridge
